apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-04-d8d9476be1d7/my-repository/hello-cloudbuild:v1.0
        ports:
        - containerPort: 8080
#